version: '3.8'

services:
  binance-connector:
    build: .
    container_name: binance-ws-connector
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      - SYMBOL=btcusdt
      - INTERVAL=1m
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - binance-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

networks:
  binance-net:
    driver: bridge